
name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Step 1 - Checkout THIS app repo
      - name: Checkout app repo
        uses: actions/checkout@v3

      # Step 2 - Login to DockerHub
      - name: Login to DockerHub
        run: |
          docker login \
            -u ${{ secrets.DOCKER_USERNAME }} \
            -p ${{ secrets.DOCKER_PASSWORD }}

      # Step 3 - Build image from Dockerfile
      # Dockerfile copies index.html into nginx:alpine image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/tap-app:${{ github.sha }} .

      # Step 4 - Push image to DockerHub with commit sha as tag
      - name: Push image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tap-app:${{ github.sha }}

      # Step 5 - Clone the CONFIG repo (argocd-kubernetes)
      # This is the SEPARATE repo that ArgoCD watches
      - name: Clone config repo
        run: |
          git clone https://x-token:${{ secrets.CONFIG_REPO_TOKEN }}@github.com/${{ secrets.CONFIG_REPO_USERNAME }}/argocd-kubernetes.git

      # Step 6 - Update image tag in BOTH dev and staging values
      - name: Update image tag in config repo
        run: |
          cd argocd-kubernetes

          # update dev values
          yq e '.image.repository = "${{ secrets.DOCKER_USERNAME }}/tap-app"' \
            -i helm/tap-app/values.dev.yaml
          yq e '.image.tag = "${{ github.sha }}"' \
            -i helm/tap-app/values.dev.yaml

          # update staging values
          yq e '.image.repository = "${{ secrets.DOCKER_USERNAME }}/tap-app"' \
            -i helm/tap-app/values.staging.yaml
          yq e '.image.tag = "${{ github.sha }}"' \
            -i helm/tap-app/values.staging.yaml

      # Step 7 - Commit and push back to CONFIG repo
      # This is what triggers ArgoCD!
      - name: Push changes to config repo
        run: |
          cd argocd-kubernetes
          git config user.email "ci@bot.com"
          git config user.name "CI Bot"
          git add helm/tap-app/values.dev.yaml \
                  helm/tap-app/values.staging.yaml
          git commit -m "ci: update tap-app image tag to ${{ github.sha }}"
          git push
